# Generated by Django 6.0.5 on 2026-05-13 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fine',
        ),
    ]
